#!/usr/bin/env bash

rm b0wter.couchdb.nuspec
set -e

GIT_TAG=$(git describe --tags --abbrev=0)
GIT_TAG=$(echo "${GIT_TAG//v}")
GIT_MESSAGE=$(sed 's/ /\\ /g' <<< $(git log -1 --pretty=%B | tr '\n' ' '))
echo "Latest tag: $GIT_TAG; Latest commit: $GIT_MESSAGE"
echo "Creating temporary nuspec file from template."
sed "s/%VERSION%/$GIT_TAG/g" b0wter.couchdb.nuspec.template > b0wter.couchdb.nuspec
sed -i 's/%RELEASE_NOTES%/'"$GIT_MESSAGE"'/g' b0wter.couchdb.nuspec

echo "Packing release."
dotnet pack -c "Release" --no-build
