# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - '*.md'
      - '*.MD'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: "Install docker-compose"
  inputs:
    targetType: 'inline'
    script: |
      sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

- task: Bash@3
  displayName: "Start a CouchDb instance"
  inputs:
    targetType: 'inline'
    script: |
      cd tests/integration
      docker-compose up -d
      scripts/up-test.sh localhost 5984
      cd -

- task: Bash@3
  displayName: "Test CouchDb connection"
  inputs:
    targetType: 'inline'
    script: |
      curl localhost:5984

- task: Bash@3
  displayName: "Build docker container"
  inputs:
    targetType: 'inline'
    script: |
      docker build -t couchdb-lib .

- task: Bash@3
  displayName: "Create test result output folder"
  inputs:
    targetType: 'inline'
    script: |
      mkdir output
      chmod -R 777 output

- task: Bash@3
  displayName: "Run tests in container"
  inputs:
    targetType: 'inline'
    script: |
      HOSTIP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
      docker run --name couchdb_tests -e COUCHDB_HOST=$HOSTIP couchdb-lib:latest
      docker cp couchdb_tests:/output/integration.xml output/

- task: PublishTestResults@2
  displayName: "Publish test results to the Azure dashboard"
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: 'output/*.xml'
    failTaskOnFailedTests: true
