# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      cd tests/integration
      docker-compose up -d
      cd -

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'CouchDb.sln'
    arguments: '-c "Release"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'CouchDb.sln'